<section class="flex">
<?php
    foreach ( $superview as $type => $mdfiles ) {
        print "<section><h3>$type</h3>";
        print <<<eob
        <table class="superview"><tr><th>Name</th><th>Type</th><th>SPs</th><th>IdPs</th><th>Refresh in</th></tr>
eob;
        foreach($mdfiles as $fed => $exts) {
            foreach($exts as $ext => $mdfile) {
            extract($mdfile);
                $test = $testphp = '';
                if ($type === 'published') {
                    $test = <<<eof
 <a href="raw?type=test&fed=$name&ext=$ext" title="$basename">*</a>
eof;
                    if ($php) {
                        $testphp = <<<eof
 <a href="raw?type=test&fed=$name&ext=php" title="$basename">*</a>
eof;
                    }
                }
                $phpfile = '';
                if ($php) {
                    $phpfile = <<<eof
 <a href="raw?type=$type&fed=$name&ext=php" title="$basename">php</a>$testphp
eof;
                }
            print <<<eob
<tr>
	<td>
		<a href="mdfileview?type=$type&fed=$name">
			$name
		</a>
	</td>
	<td>$phpfile
		<a href="raw?type=$type&fed=$name&ext=$ext" title="$basename">$ext</a>$test
	</td>
	<td>
		$sps
	</td>
	<td>
		$idps
	</td>
	<td>
		$delta
	</td>
</tr>
eob;
        }
    }
        print "</table>";
    print "</section>";
}
?>
</section>
