<section class="flex">
<?php
foreach ($superview as $path => $dirs) {
    print "<section><h3>$path</h3>";
    foreach ( $dirs as $dir => $mdfiles ) {
        print <<<eob
        <table class="superview"><tr><th>Feed</th><th>XML</th><th>SPs</th><th>IdPs</th><th>Refresh in</th></tr>
eob;
        foreach($mdfiles as $fed => $mdfile) {
            extract($mdfile);
            print <<<eob
<tr>
	<td>
		<a href="mdfileview?type=$path&fed=$name">
			$name
		</a>
	</td>
	<td>
		<a href="raw?type=$path&fed=$name" title="$basename">
			XML
		</a>
	</td>
	<td>
		$sps
	</td>
	<td>
		$idps
	</td>
	<td>
		$delta
	</td>
</tr>
eob;
        }
        print "</table>";
    }
    print "</section>";
}
?>
</section>
