<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Wayf Metadata</title>
</head>
  <body>

<script type="text/vnd.graphviz" id="cluster">
digraph G {
    rankdir=LR;
    node [nodesep=1, fontname=Helvetica, fontsize=12]

    edge [style=dotted, penwidth =3, color=green]

    <?= $helpers ?>

    edge [style=solid, color = black, penwidth = 1]

    <?= $viz ?>

    { rank=same; <?= $srcRankSame ?> };
    { rank=same; <?= $dstRankSame ?> };
    { rank=same; <?= $finalRankSame ?> };
}

</script>

    <script src="js/viz.js"></script>
    <script>

      function inspect(s) {
        return "<pre>" + s.replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;") + "</pre>"
      }

      function src(id) {
        return document.getElementById(id).innerHTML;
      }

      function example(id, format, engine) {
        var result;
        try {
          result = Viz(src(id), format, engine);
          if (format === "svg")
            return result;
          else
            return inspect(result);
        } catch(e) {
          return inspect(e.toString());
        }
      }

      document.body.innerHTML += "<h1></h1>";
      document.body.innerHTML += example("cluster", "svg");

      for (var a of document.querySelectorAll("nav a")) {
          a.classList.remove('active');
          paths = a.dataset.paths || '';
          if (a.pathname == location.pathname || paths.split(' ').indexOf(location.pathname) >= 0) {
              a.classList.add('active');
          }
      }
    </script>

  </body>
</html>
